version: 1.0.{build}
configuration: Debug 

# scripts to run before build
before_build:
    - nuget restore      #install missing nuget packages
    - '"%ProgramFiles(x86)%\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe" PreBuild\TweakAntlr.fsscript packages\Antlr4.4.5-alpha003\build\Antlr4.targets'    #fsharp script fixing Antlr4.targets file
    
build:
  project: TypeCobol.sln
  verbosity: minimal
