version: 1.0.{build}
image: Visual Studio 2022
configuration: 
  - EI_Debug
  - Debug
  - EI_Release
  - Release

cache:
  - packages -> **\packages.config
  
matrix:
    fast_finish: true
 
#AppVeyor only use this file if you use GitHub repo.
#If you use Git public repo, you must copy this lines to your build settings


# scripts to run before build
before_build:
    - dotnet restore      #install missing nuget packages
    
before_package:
    - BuildScript.bat

build:
  project: TypeCobol.sln
  verbosity: minimal
  
  # To uncomment to activate Remote Desktop, will be deleted on job completed
#before_test:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
  #To uncomment to block the job on test failure, so the Remote Desktop remains after test
  #To continue the job, you have to delete a .txt on the Remote Desktop session located on the desktop
#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
artifacts: 
  - path: bin\EI_TypeCobol_Release
    name: EI_TypeCobol_Release
  - path: bin\TypeCobol_Release
    name: TypeCobol_Release

deploy:
  provider: GitHub
  auth_token: 
    secure: oX7Ck0VMD2HvWjA2Itqc+95Azad6jIkr6C0uMLoq0gK9kKfK+UIXWvwqM6oenhkG
  artifact: EI_TypeCobol_Release,TypeCobol_Release
  draft: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only

